name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'  # triggers on every push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configure AWS credentials for subsequent AWS CLI commands and ECR login
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Login to Amazon ECR Public (uses the AWS-provided action for public registries)
      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      # Build the Docker image (assumes a Dockerfile in the repository root)
      - name: Build Docker Image
        run: |
          docker build -t silentwhisperer .

      # Tag the Docker image using your desired format
      - name: Tag Docker Image
        env:
          ECR_REGISTRY: public.ecr.aws/your_ecr_repo_uri  # Replace with your ECR repository URI
          IMAGE_NAME: silentwhisperer
        run: |
          docker tag giftedlabs/wk4-lab1:latest $ECR_REGISTRY/$IMAGE_NAME:latest

      # Push the Docker image to your public ECR repository
      - name: Push Docker Image to ECR Public
        env:
          ECR_REGISTRY: 650251709711.dkr.ecr.us-west-2.amazonaws.com  # Replace with your ECR repository URI
          IMAGE_NAME: silentwhisperer
        run: |
          docker push $ECR_REGISTRY/$IMAGE_NAME:latest
