name: Build and Push to Public ECR

on:
  push:
    branches:
      - '**'  # triggers on every push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Configure AWS Credentials (make sure to use us-east-1 for Public ECR)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3) Login to Amazon ECR Public
      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      # 4) Build the Docker image (using a Dockerfile in the repo root)
      - name: Build Docker Image
        run: |
          docker build -t week4-lab1 .

      # 5) Tag the Docker image with your public ECR repo name
      - name: Tag Docker Image
        run: |
          docker tag week4-lab1:latest public.ecr.aws/r1b3l1w9/week4-lab1:latest

      # 6) Push the Docker image to your public ECR repository
      - name: Push Docker Image
        run: |
          docker push public.ecr.aws/r1b3l1w9/week4-lab1:latest
