name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'  # triggers on every push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Configure AWS credentials (make sure you have AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY set in repo secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # 3) Log in to your PRIVATE ECR repository in us-west-2
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-west-2 \
            | docker login --username AWS --password-stdin 650251709711.dkr.ecr.us-west-2.amazonaws.com

      # 4) Build the Docker image (Dockerfile is assumed to be in the root of the repo)
      - name: Build Docker Image
        run: |
          docker build -t giftedlabs/wk4-lab1 .

      # 5) Tag the Docker image with your ECR repository name
      - name: Tag Docker Image
        run: |
          docker tag giftedlabs/wk4-lab1:latest 650251709711.dkr.ecr.us-west-2.amazonaws.com/giftedlabs/wk4-lab1:latest

      # 6) Push the Docker image to your ECR repository
      - name: Push Docker Image
        run: |
          docker push 650251709711.dkr.ecr.us-west-2.amazonaws.com/giftedlabs/wk4-lab1:latest
